project/cliente/urls.py
from django.urls import path
from . import views

app_name = "cliente"

urlpatterns = [
    path("", views.home, name="index"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('producto/', include("producto.urls")),
    path('cliente/', include("cliente.urls")),
]

project/core/urls.py
from django.urls import path
from . import views

app_name = "core"


urlpatterns = [
    path("", views.home, name="index"),
]

project/producto/urls.py
from django.urls import path
from . import views

app_name = "producto"

urlpatterns = [
    path("", views.home, name="index"),
]

project/cliente/models.py
from django.db import models

class pais(models.Model):
    nombre = models.CharField(max_length=100, unique=True)


class cliente(models.Model):
    nombre = models.CharField(max_length=100),
    apellido = models.CharField(max_length=100),
    nacimiento = models.DateField(null=True, blank=True)
    pais_origen = models.ForeignKey(pais, on_delete=models.SET_NULL, null=True, blank=True)

project/core/models.py
from django.db import models

# Create your models here.

project/producto/models.py
from django.db import models

# Create your models here.

project/cliente/views.py
from django.shortcuts import render


def home(request):
    return render(request, "cliente/index.html")

project/core/views.py
from django.shortcuts import render


def home(request):
    return render(request, "core/index.html")

project/producto/views.py
from django.shortcuts import render


def home(request):
    return render(request, "producto/index.html")

project/cliente/templates/cliente/index.html
{% extends 'core/base.html' %}

{% block contenido_titulo %} 
    CLIENTE
{% endblock contenido_titulo %}

{% block contenido %}
    <ul>
        <a href="{% url 'core:index' %}">volver al inicio</a>
    </ul>
{% endblock contenido %}

project/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AppCore</title>
</head>
<body>

    <h1 style="color:green">
        {% block contenido_titulo %}
        {% endblock contenido_titulo %}
    </h1>

    {% block contenido %}
    {% endblock contenido %}

    {% block footer %}
        <p>Hecho en 2023</p>
    {% endblock footer %}
</body>
</html>

project/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block contenido_titulo %} 
    CORE
{% endblock contenido_titulo %}

{% block contenido %}
    <ul>
        <li><a href="{% url 'cliente:index' %}">Ir a CLIENTE</a></li>
        <li><a href="{% url 'producto:index' %}">Ir a PRODUCTO</a></li>
    </ul>
{% endblock contenido %}

   

project/producto/templates/producto/index.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}
   PRODUCTO
{% endblock contenido_titulo %}

{% block contenido %}
    <a href="{% url 'core:index' %}">volver al inicio</a>
{% endblock contenido %}